package com.company.commands.enums;

public enum CommandType {
    ADD_COMMENT,
    ADD_PERSON_TO_TEAM,
    ASSIGN_TASK_TO_PERSON,
    CHANGE_PRIORITY,
    CHANGE_RATING,
    CHANGE_SEVERITY,
    CHANGE_SIZE,
    CHANGE_STATUS,
    CREATE_BOARD_IN_TEAM,
    CREATE_BUG,
    CREATE_FEEDBACK,
    CREATE_PERSON,
    CREATE_STORY,
    CREATE_TEAM,
    SHOW_ALL_PEOPLE,
    SHOW_ALL_TEAM_BOARDS,
    SHOW_ALL_TEAM_MEMBERS,
    SHOW_ALL_TEAMS,
    SHOW_BOARD_ACTIVITY,
    SHOW_PERSON_ACTIVITY,
    SHOW_TEAM_ACTIVITY,
    UNASSIGN_TASK_FROM_PERSON
}
